### ISSUE TITLE
Using an alternative ID

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#106]
When using two "IDs": one is the real ID for the database and the other is the ID exposed to the API, for example with an entity `User` for which the database ID is `id` and the "API ID" is `username`, the `DataProvider` should be extendable or have the necessary operations to avoid any dumb copy/paste.

**Comment by theofidry** [comment]
@dunglas If I'm not wrong it has been dealt with 2d60104618e78423e1ea6cbdbe8250280cac638b no?

**Comment by dunglas** [comment]
Yes.
