### ISSUE TITLE
How to authorize some field on resource creation but block them on modification ?

### ISSUE THREAD

**Issue by MLKiiwy** [dunglas/DunglasApiBundle#117]
For example : on user creation i set the password field (POST operation). But i want to remove the possibility of modifying this field on PUT / PATCH operations.

There is an existing feature or a trick to do this actually ?

**Comment by dunglas** [comment]
It's not supported directly because Hydra don't have such difference. However a trick exist:
- register a custom normalizer
- in that normalizer, check if `$context['object_to_populate']` is set (update) or not (create) and adapt the code

**Comment by MLKiiwy** [comment]
Thanks for the tip : yes, it's a solution 
 
But after reflexion, my issue was to avoid change on the entity ... so I move the security process into doctrine layer with an event listener on preUpdate. I check if field have change and throw an exception on field that must no change. 

Maybe, put a "Question" label on this issues and archive it for information.

**Comment by dunglas** [comment]
Thank you for the feedback.

For "support" like that, I'm thinking about using StackOverflow with #ApiPlatform hashtag. It will make replies available to a broader audience.
 What do you think?

**Comment by MLKiiwy** [comment]
Yes ! StackOverflow is the right place for that ! 
But maybe a tag #DunglasApiBundle ?

**Comment by dunglas** [comment]
Let's go for both: #apiPlatform #dunglasApiBundle #symfony :-) They are all relevant!
