### ISSUE TITLE
Error when i'm trying to install bundle

### ISSUE THREAD

**Issue by jokari4242** [dunglas/DunglasApiBundle#124]
Hello,

I have this error, do you have an idea?

CRITICAL - Fatal Parse Error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH) 
CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected 'finally' (T_STRING), expecting catch (T_CATCH)" at /vendor/dunglas/api-bundle/Routing/Router.php line 75 

Thanks!

**Comment by sroze** [comment]
You're using a too old version of PHP :)

**Comment by jokari4242** [comment]
Whaouu thanks very fast answer! indeed it works much better!
