### ISSUE TITLE
Share the Response in events

### ISSUE THREAD

**Issue by Ener-Getick** [dunglas/DunglasApiBundle#128]
I think that it could be nice to share the ``Response`` in events.

For example, if we want to add some custom headers based on the data (like ``Last-Modified``), we must actually extends the ``ResourceController``.

But sharing the response cause a problem: the data could be edited so the ``Response`` content must be defined after the propagation.

So there is an example of implementation :

```php
    public function getAction(Request $request, $id)
    {
        $resource = $this->getResource($request);
        $object = $this->findOrThrowNotFound($resource, $id);
        $response = $this->getSuccessResponse()

        $this->get('event_dispatcher')->dispatch(Events::RETRIEVE, new DataEvent($resource, $object, $response));

        return $this->handleResponse($resource, $object);
    }
```

**Comment by sroze** [comment]
Given your use case, I'd advice you to have a more generic option such as a kernel event listener on the `kernel.response` event.

**Comment by Ener-Getick** [comment]
I'd like to add a ``Last-Modified`` header. 
The problem of the kernel event listener is that we can't to access the raw data so the object fields. We could maybe use the serialized data but for that we need to deserialize it ...

**Comment by dunglas** [comment]
@Ener-Getick you closed the ticket, have you found a solution?

**Comment by Ener-Getick** [comment]
@dunglas yes, finally, I just listen to ``kernel.response`` and ``api.retrieve``. I saved the api data and reused it to update the ``Response``.  
It's less clean but it works.

I reopen this issue in the case that you prefer a cleaner way.

**Comment by dunglas** [comment]
@Ener-Getick the way you do it is clean IMO. Events from the bundle are "API business" events. Using Symfony kernel events for manipulating the HTTP response looks good to me.

I'm not confortable to make events of the bundle aware of the HTTP response. It's not their responsibility.

**Comment by sroze** [comment]
@dunglas Totally agree.
