### ISSUE TITLE
PUT and partial updates

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#134]
Consider this JSON fragment:

```
{
"name": "test1123",
  "prefixes":[ {
    "@id": "/~felicitus/PartKeepr/web/app_dev.php/api/si_prefixes/8",
  }]
}
```

In my installation, the bundle tries to create a new entity instead of loading the existing one specified by @id. According to the documentation [here](https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/serialization-groups-and-relations.md#denormalization), this should work.

When I change my JSON to 
```
{
"name": "test1123",
  "prefixes": [
       "/~felicitus/PartKeepr/web/app_dev.php/api/si_prefixes/8"
    ]
}
```

it works, but that prevents me from updating related objects, as they are always considered new.

**Comment by dunglas** [comment]
Do you send this JSON fragment trough a `POST` or a `PUT` request?
Can you post your service definition and your entities (especially groups definition) to see what is going wrong?

**Comment by felicitus** [comment]
I'm using a PUT request, I haven't tested POST so far.

[config.yml](https://github.com/partkeepr/PartKeepr/blob/sf2migration-dunglas/app/config/config.yml#L104)
[Unit.php](https://github.com/partkeepr/PartKeepr/blob/sf2migration-dunglas/src/PartKeepr/UnitBundle/Entity/Unit.php)
[SiPrefix.php](https://github.com/partkeepr/PartKeepr/blob/sf2migration-dunglas/src/PartKeepr/SiPrefixBundle/Entity/SiPrefix.php)

In the meanwhile, I tried different things like making properties public and removing getters/setters, but it didn't seem to work. Most likely a PEBCAK, but I couldn't figure it out. Thanks for your help!

**Comment by dunglas** [comment]
Thank for the report, it was a bug! Fixed in master.

**Comment by felicitus** [comment]
Thank you for the quick fix, I can confirm that it works now.
