### ISSUE TITLE
Status code 202 for PUT operation ?

### ISSUE THREAD

**Issue by iamluc** [dunglas/DunglasApiBundle#136]
Hi,

I think PUT operation should returns a status code 200 instead of 202 by default.
From my understanding, 202 is for delayed processing, and it does not seem to be the most common usecase.

Could we at least make it configurable ?

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#2xx_Success

**Comment by dunglas** [comment]
You're right, must be changed to 200.

**Comment by jderusse** [comment]
Should be reopened for branch master

**Comment by jderusse** [comment]
Already fixed, nevermind...
