### ISSUE TITLE
Behat test incompatible with ext-jsonc

### ISSUE THREAD

**Issue by iamluc** [dunglas/DunglasApiBundle#138]
The behat tests suite fails with extension jsonc installed (https://pecl.php.net/package/jsonc)

The problem is in ***Scenario: Get an error because of an invalid JSON*** (error.feature)
```
And the JSON node "hydra:description" should be equal to 'Syntax error'
    The node value is `"unexpected character"` (Exception)
```

(https://github.com/remicollet/pecl-json-c/blob/master/json-c/json_tokener.c#L62)

**Comment by dunglas** [comment]
IMO you should open a bug on the JSONC bug tracker instead of here.
But if necessary fix the Behat assertion to allow both messages.

**Comment by iamluc** [comment]
I think it is needed to be fixed here, as php5-json is a dependency of php5-fpm, php5-cli etc... on Debian Jessie.

**Comment by dunglas** [comment]
php5-json is the builtin PHP JSON extension isn't it?

**Comment by iamluc** [comment]
No it's not.
The homepage and the version in https://packages.debian.org/jessie/php5-json point to https://pecl.php.net/package/jsonc

**Comment by dunglas** [comment]
Ok. So the text must be fixed to ignore the returned message.
