### ISSUE TITLE
Search filter for all fields

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#140]
In the order filter, one can specify `~` to indicate that ordering for any field should be supported.

The sort filter doesn't seem to support that feature, would it be possible to have this added, or should I rather implement an own filter?

**Comment by dunglas** [comment]
It's supported by all existing filters: https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/filters.md#enabling-a-filter-for-all-properties-of-a-resource

**Comment by felicitus** [comment]
Gotcha. However, specifying exact and partial isn't supported in that scenario, correct? Also, I guess that specifying "all fields must be exact matches, but fields X and Y can be partial matches" isn't possible?

**Comment by dunglas** [comment]
Exactly.

**Comment by felicitus** [comment]
I think I need to implement an own filter class for that. Thank you!
