### ISSUE TITLE
Pass object for PUT operations

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#144]
For one of our project, instead of passing the following data for a PUT `/dummies/1`:
```json
{
    "name": "New name"
}
```

We were passing the whole object, with the new values:
```json
{
  "@context": "\\/contexts\\/Dummy",
  "@id": "\\/dummies\\/1",
  "@type": "Dummy",
  "name": "New name",
  "alias": "Lorem ipsum"
}
```

But since a recent upgrade, this doesn't work anymore. Is it supposed to works or was it a misuse of our part?

**Comment by dunglas** [comment]
It must work. If it doesn't it's a bug.

**Comment by theofidry** [comment]
Ok, I'll dig into that then. I'm pretty sure it's an edge case with embedded relations and serialization groups.

I was a little surprised though. It's it a common RESTful practice?

**Comment by theofidry** [comment]
I don't remember what the issue was but it's now solved.
