### ISSUE TITLE
[Serializer] Unescape slashes in json by default

### ISSUE THREAD

**Issue by rolebi** [dunglas/DunglasApiBundle#170]
I was wondering why `JSON_UNESCAPED_SLASHES` is not used by default by the json encoder ?

A little gain of bandwidth and a big + for readability.

**Comment by dunglas** [comment]
This task is delegated to Symfony (which is delegating to PHP `json_encode()`). IMO it's safer to leave it as is: less readable but secure in any case, even when embedding API return in HTML for instance.
It's also less maintenance to not override this part of Symfony.

Btw, the API return is compressed, to using a prettyfier like the one provided by Postman is a good idea to debug.

**Comment by rolebi** [comment]
Got it. btw already using Postman ^^
