### ISSUE TITLE
[Question] How do you manage to implement authorization ?

### ISSUE THREAD

**Issue by Malikros** [dunglas/DunglasApiBundle#182]
Hi,

I want to give the bundle a try, but I can't figure out how to implement authorization without breaking everything. I've used the LexikJWT bundle without problems, but how do I manage to limit certain actions to certain roles ? 
I figured that if I want to use voters, I could use my own controller or Resource but it seems quite troublesome.
Any idea ? 

(In a more concrete way, I'm kinda looking for a built-in option to do this, one that I could configure in the same way than the rest...)

Thanks ! (And great work by the way)

**Comment by dunglas** [comment]
There is 2 possible ways:

* for simple case, specify the role and credentials you want in `app/config/security.yml`: http://symfony.com/doc/current/book/security.html#securing-url-patterns-access-control Thanks to the REST architecture, it should be very straightforward.
* if you have more advanced needs, use Symfony and ApiBundle events: https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/the-event-system.md

Creating a custom controller should be your last resort (this is considered bad practice).

**Comment by theofidry** [comment]
As it's a recurrent question, maybe it would be worth to add a little word on it in the doc with one or two example.

**Comment by dunglas** [comment]
It definitely deserves an exhaustive cookbook entry!

**Comment by Malikros** [comment]
Ok, so I could implement the check against the voters in an event listener. Got it.
Thanks.

For me the issue is solved, do you want to leave it open for the doc-editing part ?

**Comment by dunglas** [comment]
Leave it open please.

**Comment by theofidry** [comment]
Yep keep it open for now :)
