### ISSUE TITLE
Call to undefined method JMS\Serializer\Serializer::normalize()

### ISSUE THREAD

**Issue by stevro** [dunglas/DunglasApiBundle#190]
Is this bundle incompatible with JMS Serializer or I've done something wrong? I'm using Symfony REST Edition.

**Comment by dunglas** [comment]
Hi,

This bundle doesn't use JMSSerializer (it uses the Serializer of Symfony) but should not cause compatibility issues with it.
I strongly recommend you to use [the API Platform edition](https://github.com/dunglas/api-platform) instead of the REST edition. It comes with this bundle and other useful tools to create an API preconfigured.

Can you give us more information about the error (the full stack trace)?

**Comment by stevro** [comment]
It seems to be coming from the ResourceController.

2015/07/25 16:22:32 [error] 11173#0: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method JMS\Serializer\Serializer::normalize() in /home/stefan/bloc/vendor/dunglas/api-bundle/Controller/ResourceController.php on line 87
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /home/stefan/bloc/web/app_dev.php:0
PHP message: PHP   2. Symfony\Component\HttpKernel\Kernel->handle() /home/stefan/bloc/web/app_dev.php:25
PHP message: PHP   3. Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle() /home/stefan/bloc/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202
PHP message: PHP   4. Symfony\Component\HttpKernel\HttpKernel->handle() /home/stefan/bloc/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php:69
PHP message: PHP   5. Symfony\Component\HttpKernel\HttpKernel->handleRaw() /home/stefan/bloc/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68
PHP message: PHP   6. call_user_func_array() /home/stefan/bloc/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:147
PHP message: PHP   7. Dunglas\ApiBundle\Controller\ResourceController->cgetAction() /home/stefan/bloc/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:147
PHP message: PHP   8. Dunglas\ApiBundle\Controller\ResourceController->getSuccessResponse() /home/stefan/bloc/vendor/dunglas/api-bundle/Controller/ResourceController.php:161" while reading response header from upstream, client: 192.168.56.1, server: api.bloc.local, request: "GET /app_dev.php/api/consumators?_format=json HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "api.bloc.local", referrer: "http://api.bloc.local/app_dev.php/api/doc"
2015/07/25 16:22:32 [error] 11173#0: *1 upstream sent too big header while reading response header from upstream, client: 192.168.56.1, server: api.bloc.local, request: "GET /app_dev.php/api/consumators?_format=json HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "api.bloc.local", referrer: "http://api.bloc.local/app_dev.php/api/doc"

**Comment by ogizanagi** [comment]
@dunglas : It will actually cause compatibility issue, as the JMSSerialiser registers itself through an alias as the `serializer` service id: https://github.com/schmittjoh/JMSSerializerBundle/blob/master/Resources/config/services.xml#L178

So, the mention error certainly occurs [here](https://github.com/dunglas/DunglasApiBundle/blob/master/Controller/ResourceController.php#L87)

**Comment by ogizanagi** [comment]
@stevro : you should probably disable the short service name in the bundle configuration:
```yaml
jms_serializer:    
    enable_short_alias: false
```

**Comment by stevro** [comment]
@ogizanagi I did that and it works. Thanks

**Comment by aequasi** [comment]
Can we get this added to the documentation please! Thanks :)

**Comment by teohhanhui** [comment]
@aequasi PR welcome :)
