### ISSUE TITLE
Unable to generate an IRI in EntryPointBuilder

### ISSUE THREAD

**Issue by pvgnd** [dunglas/DunglasApiBundle#203]
EntryPointBuilder loops over all resource types and try to build IRI.
But, if no collection operations is declared on a resource type, the IRI Converter is not able to generate an IRI.

Maybe the EntryPointBuilder should check if the resource type has at least one collection operation ?
 - Add a hasCollectionOperation() helper method on Resource Class and Resource Interface
 - Call this helper method before trying to add the resource type to the entry points list

I can provide a PR if you agree with this.

**Comment by ogizanagi** [comment]
:+1: 

What would be the behavior in case the resource type does not have any collection operation ?
It will simply be ignored in the entrypoint ?

**Comment by pvgnd** [comment]
@ogizanagi yes

**Comment by dupuchba** [comment]
good catch, but how do you check that one resource has no collection ?

**Comment by ogizanagi** [comment]
@dupuchba : `empty($resource->getCollectionOperations())`

**Comment by dupuchba** [comment]
:+1:

**Comment by pvgnd** [comment]
should I introduce a BC Break by adding the hasCollectionOperations() and hasItemOperations() or do you prefer the empty($resource->getCollectionOperations()) in the EntryPointBuilder ?

**Comment by theofidry** [comment]
Closing as fixed via #205.
