### ISSUE TITLE
Doc issue: register a custom format

### ISSUE THREAD

**Issue by ogizanagi** [dunglas/DunglasApiBundle#210]
I think there is an issue with the way the [documentation explains how to register a custom format in the Negotiation library](https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/doc/content-negotiation.md#registering-a-custom-format-in-the-negotiation-library) : You can't access definitions from other bundles from an extension, as you only have a [tmp Container builder](https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/DependencyInjection/Compiler/MergeExtensionConfigurationPass.php#L55) instance in the `ExtensionInterface::load` method.

Thus, this instance only contains parameters, and services you loaded through files:
```php
$loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
$loader->load('services.yml'); // Only services declared here are accessible in the container builder from the extension.
```

So, we would need either to:
- explain how to create a compiler pass in order to execute this piece of code:
```php
$container->getDefinition('api.format_negotiator')->addMethodCall('registerFormat', [       
    'myformat', ['application/vnd.myformat'], true,     
]);     
```

- expose a configuration to register custom formats.

**Comment by dupuchba** [comment]
Good catch, :+1: with this

**Comment by dunglas** [comment]
Good catch. The compiler pass looks the better way IMO.
