### ISSUE TITLE
extendable DataProvider

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#22]
Would it be possible to make the properties and functions of `DataProvider` `protected` instead of `private` or it has been made so on purpose?

**Comment by sroze** [comment]
@theofidry Why do you need these properties to be protected and what's your use case of extending the ORM data provider (because I think that's the answer of the first question :)) ?

**Comment by theofidry** [comment]
For instance I which to add a function `public function getItemBySlug($slug)` to my DataProvider and for that I need to access to `resource` and `managerRegistry` that are currently private. As a consequence I have to declare my own `DataProvider` and copy/paste all the content of `DataProvider` of the the bundle to do so.

**Comment by dunglas** [comment]
@sroze custom logic for filtering and ordering for instance.
I would prefer making protected getters than direct access to properties.

**Comment by theofidry** [comment]
@dunglas Any change regarding this point with the upgrade?

**Comment by dunglas** [comment]
Yes. I think this bug is not relevant any more as you can create custom data providers and custom filters.

**Comment by theofidry** [comment]
Ok, I'm taking care of rebasing the order filter and will check this point later then.

**Comment by theofidry** [comment]
With the change in the way URL queries are handled (cf. PR #43), we do not have the need to extend the DataProvider anymore.

However maybe adding getters for `resources` and `managerRepository` would avoid any problem if one which to do so.
