### ISSUE TITLE
Null and empty values for order filters

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#238]
We already encountered the issue with the `DateFiler`: when ordering a collection by a property, we currently left all the management of null and empty values. This is a problem as the order may depend form a database to another and we currently have no control on it.

**Comment by teohhanhui** [comment]
I'm not sure if you can even have such control over the `ORDER BY` clause... This might be unfixable.

**Comment by teohhanhui** [comment]
http://stackoverflow.com/questions/319384/database-consistency-with-sql-order-by-and-nulls

**Comment by theofidry** [comment]
Then as for #241: it's something we don't really have control on and too specific which we shouldn't bother with, we should at least say a word of it in the doc.

**Comment by theofidry** [comment]
Closing as is now mentioned in [filter#managing-null-values](https://api-platform.com/doc/1.0/api-bundle/filters#managing-null-values).
