### ISSUE TITLE
Stop swallowing exceptions

### ISSUE THREAD

**Issue by teohhanhui** [dunglas/DunglasApiBundle#243]
When an exception is handled by `Dunglas\ApiBundle\Hydra\EventListener\RequestExceptionListener` I can't see what went wrong from the profiler, because the exception is not being logged.

It's as if no exception has ever occurred. That cannot be right.

**Comment by teohhanhui** [comment]
TL;DR We're doing it wrong

http://symfony.com/doc/current/components/http_kernel/introduction.html#handling-exceptions-the-kernel-exception-event

> ##### ExceptionListener in HttpKernel
>
> The first comes core to the HttpKernel component and is called [ExceptionListener](http://api.symfony.com/2.7/Symfony/Component/HttpKernel/EventListener/ExceptionListener.html). The listener has several goals:
>
> 1. The thrown exception is converted into a [FlattenException](http://api.symfony.com/2.7/Symfony/Component/HttpKernel/Exception/FlattenException.html) object, which contains all the information about the request, but which can be printed and serialized.
> 2. If the original exception implements [HttpExceptionInterface](http://api.symfony.com/2.7/Symfony/Component/HttpKernel/Exception/HttpExceptionInterface.html), then `getStatusCode` and `getHeaders` are called on the exception and used to populate the headers and status code of the `FlattenException` object. The idea is that these are used in the next step when creating the final response.
> 3. A controller is executed and passed the flattened exception. The exact controller to render is passed as a constructor argument to this listener. This controller will return the final `Response` for this error page.

We should refer to FOSRestBundle's [ExceptionController](https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Controller/ExceptionController.php)

**Comment by dunglas** [comment]
Good catch! Can you work to fix that?

**Comment by teohhanhui** [comment]
Would love to hear from someone who's really familiar with this before I do...
