### ISSUE TITLE
Unable to customize data before deserialize

### ISSUE THREAD

**Issue by bwegrzyn** [dunglas/DunglasApiBundle#246]
I have several entities that have hard requirements in the form of constructor arguments that need to be injected by the server before an entity can be created. These arguments are computed by the server as it is not something that you can trust a user with. For example, the account an entity belongs to is computed from the subdomain + auth details on a SaaS application and is a required constructor argument for the User entity.

The symfony serializer component seems to support this use case, but requires the arguments be part of the data passed for deserialization. This seems to be the case both when creating a new object, and when deserializing in to an existing object. DunglasApiBundle on the other hand doesn't seem to provide a method to modify the data it passes to the serializer component to enable this. 

The only work around I can find is to remove the constructor arguments and use a pre_create/pre_update event to inject the arguments in to settings on the entity.

Any ideas on how to make this work or what is needed to support this use case?

**Comment by dunglas** [comment]
I'm not sure to understand well but the bundle extends the `abstract` class provided by the Symfony Serializer component and has the same behavior for serializing and deserializing.
If the data is present in the JSON-LD document, it will be passed to the entity constructor.

**Comment by bwegrzyn** [comment]
Yes, I understand that. However, sometimes there is required data that cannot be trusted to be provided by the end user using the API.

User
- account_id
- name
- email

The account_id property is part of the constructor and is computed by the server from the subdomain the API was accessed on (https://myaccount.domain.com/api/...) and the authentication details provided by the user.

If account_id was part of the JSON-LD document then the authenticated user could start creating and editing User entities for accounts outside of their own.

**Comment by dunglas** [comment]
Got it. IMO `account_id` should not be part of the entity but externalized in a service. But if you cannot refactor it to extract the business logic from structure holding customer data, the only solution I see is creating a custom normalizer (extending normalizers provided by the bundle) that will inject the value you need in the entity constructor.

**Comment by bwegrzyn** [comment]
I think writing a custom normalizer to handle this would work.

But I'm curious about what you mean by moving `account_id` to an external service? That property is a `@ManyToOne` doctrine relation to the Account entity and is saved in a database field `account_id`. How do you propose moving this out of the entity?
