### ISSUE TITLE
Releasing 1.0 and creating a new 2.0 branch

### ISSUE THREAD

**Issue by dunglas** [dunglas/DunglasApiBundle#253]
Hi everybody,

The `1.0.0 beta3` version is pretty stable now and used in production on a lot of projects. However there are a lot of BC breaks in `dev-master` (ADR pattern, immutable metadata system) and I'll add more soon (move `Resource` and `Operation` in the metadata system, decoupling from Symfony, using an external library).

A lot of projects (including commercial projets at least at Les-Tilleuls.coop) are based on the beta3 and the migration to `dev-master` will be hard because of the BC breaks. As I don't want to maintain a compatibility layer now (it's doable but will be a lot of work) I propose the following strategy:

Doing like this will more in the spirit of [semver](http://semver.org/) too.
* Create a 1.0 branch starting from 1.0.0 beta3 and release a 1.0.0 version (stable).
* The `master` branch will become 2.0 when ready

I plan to that this week. What do you think?

cc @sroze @theofidry @ogizanagi @csarrazi

**Comment by dupuchba** [comment]
It sounds great to me. Move fast to make a great library and have more traction.

But you'll have to communicate on this facts on homepage IMO.

**Comment by csarrazi** [comment]
Agreed. Regardless, a new release should not introduce BC breaks with `beta`-flagged releases, whereas it is still possible with `alpha` releases.

`dev-master` should be aliased to `2.0.x-dev`, and a 1.0 branch created. This will let us work on documenting the upgrade path towards `2.0`, by linking to both the stable and unstable versions of the code (see https://github.com/csarrazi/CsaGuzzleBundle#documentation for an example).

**Comment by MLKiiwy** [comment]
Agree too, create a 1.0 branch and made ```dev-master``` should be aliased to ```2.0.x-dev```

**Comment by csarrazi** [comment]
Regardless, this doesn't change the fact that we can (and should) change the repository's owner to the @api-platform org.

**Comment by dupuchba** [comment]
:+1:

**Comment by sroze** [comment]
I agree with @csarrazi, it may be better to move `dev-master` to the @api-platform organisation and keep this repository for 1.0.0 that can be released from 1.0.0 beta3.

**Comment by csarrazi** [comment]
For this, we should *replace* the original package in new repository's `composer.json`.

See https://getcomposer.org/doc/04-schema.md#replace

**Comment by csarrazi** [comment]
Or deprecate the old vendor, to prompt users to use the new one.

**Comment by csarrazi** [comment]
See https://github.com/composer/packagist/issues/192 and https://github.com/composer/composer/pull/3325

**Comment by ogizanagi** [comment]
@dunglas : What do you think of a `1.0.0 beta4` release before doing the big BC break about Resources and Operations into the metadata system ? 
The current `dev-master` brings some great improvements thanks to the query extensions stuff, the ADR pattern [and so on](https://github.com/dunglas/DunglasApiBundle/compare/v1.0.0-beta.3...master). 
The small BC breaks in there are quite straightforward and transparent for the classic usage of the bundle, except the disappearance of the `ResourceController`. The only point is that the NelmioApiDoc support is totally broken and means that something should be done about it.
Or, it might make more sense for it to be part as a alpha release of the `2.0` **before** the big refactoring of Resources and Operations ?

**Comment by csarrazi** [comment]
@ogizanagi Even though there are great improvements in the dev-master branch, if we want to use a tagged version, it should be as an `alpha` release of the `2.0` version, and not as the fourth beta of release `1.0`. It makes more sense, as we should not introduce BC breaks as long as we start using `beta` releases in a branch.

Regardless, I do no see any issue in having a 2.0.0-alpha1 release before refactoring of Resources and Operations.

Otherwise, if we **want** to support forward compatibility, we could also have some work done to ensure compatibility between the latest beta in the dev-master branch, and drop the compatibility layer in `2.0`. What do you think about it, @ogizanagi @dunglas @sroze @theofidry ?

![https://cloud.githubusercontent.com/assets/1210224/7501070/ec1cd2cc-f431-11e4-94a3-fdd75c64db5f.png](https://cloud.githubusercontent.com/assets/1210224/7501070/ec1cd2cc-f431-11e4-94a3-fdd75c64db5f.png)

**Comment by ogizanagi** [comment]
Totally approved :+1:

**Comment by dunglas** [comment]
:+1: 

To sum up:
* mark 1.0 here
* 1.0 stay in that repository
* create 2 new repos: `api-platform/core` (the standalone library) and `api-platform/ApiPlatformBundle` (the Symfony integration)
* Mark `api-platform/ApiPlatformBundle` as a replacement of `dunglas/DunglasApiBundle` in its `composer.json`
* When the first release version of both `api-platform/ApiPlatformBundle` and `api-platform/core` will be marked as 2.0 to not be mingled with code in the `dunglas` namespace.

Extra question: how many time do we maintain 1.0?

**Comment by theofidry** [comment]
> To sum up:
>  * mark 1.0 here
  * 1.0 stay in that repository
  * create 2 new repos: api-platform/core (the standalone library) and api-platform/ApiPlatformBundle (the Symfony integration)
  * Mark api-platform/ApiPlatformBundle as a replacement of dunglas/DunglasApiBundle in its composer.json
  * When the first release version of both api-platform/ApiPlatformBundle and api-platform/core will be marked as 2.0 to not be mingled with code in the dunglas namespace.

:+1: 

> Extra question: how many time do we maintain 1.0?

I don't have much experience in that and I guess it also depends of how much traction there is. I guess a few months (3?) after the `2.0` is out (depends of how fast we ship the `2.0`).

**Comment by dupuchba** [comment]
And @dunglas , when can we start to work on core lib ?

**Comment by dunglas** [comment]
I've already started. I'll try to finish the decoupling this week then we can start to split the bundle and the lib.

**Comment by csarrazi** [comment]
I would actually mark 1.0 in the new org, and not here. We should tell people upfront that the repository will be migrated from `api-platform`, and not `dunglas`. This way, users will have a deprecation notice directly when running composer install on their local machines.

This is done very easily in packagist's package management webpage.

**Comment by dunglas** [comment]
But what is the advantage to force projects to upgrade to a new namespace for 1.0? When 1.0 will be at its EOL `dunglas/DunglasApiBundle` can still be marked as deprecated and point to the new org.

**Comment by csarrazi** [comment]
Oh, right. I completely omitted the fact that namespaces will have to change, also...

**Comment by csarrazi** [comment]
Ok for me, then!

**Comment by dunglas** [comment]
And the 1.0 branch is here: https://github.com/dunglas/DunglasApiBundle/tree/1.0

Can you test it before I mark the first stable release?
