### ISSUE TITLE
AttributesLoader doesn't recognize Entity as writable

### ISSUE THREAD

**Issue by Gregcop1** [dunglas/DunglasApiBundle#255]
In a manytomany relation :
```
    /**
     * @ORM\ManyToMany(targetEntity="Keyword", mappedBy="posts", cascade={"all"})
     */
    private $keywords;
```
with only add/remove/get functions, [AttributesLoader doesn't recognize the entity as writable](https://github.com/dunglas/DunglasApiBundle/blob/v1.0.0-beta.3/Mapping/Loader/AttributesLoader.php#L71).
Writing a setter for this property solves the problem.

**Comment by theofidry** [comment]
@Gregcop1 not sure to get your problem: if the property is `public` it will be used as such, otherwise a mutator will be looked for.

**Comment by dunglas** [comment]
@Gregcop1 is this problem still of actuality?

**Comment by Gregcop1** [comment]
I'll check this at 12.

**Comment by Gregcop1** [comment]
I've tried to reproduce the issue (it's been a while so I've half-forgotten ;)) but It seems to be OK now. You can close this one

**Comment by dunglas** [comment]
Thanks
