### ISSUE TITLE
Sort some resources in an additional tree

### ISSUE THREAD

**Issue by jewome62** [dunglas/DunglasApiBundle#258]
Hi!

I would know if it's possible, to sort some resources in other tree.

I would have public API in /api/
And a private API in /api/internal/

Is there a trick to do this ?

thanks

**Comment by dunglas** [comment]
I don't think it's possible now (even with the v2, not sure if it's doable).

However you can setup a fine grained access control to some URLs using the Symfony firewall. E.g.: anonymous can access to /api, users with `ROLE_USER` to /api/internal and admins with `ROLE_ADMIN` to `/api/internal/admin`.
 
An alternative would be to create two applications (one by API).

**Comment by jewome62** [comment]
I have already two firewall, one for /api/ allowed for ROLE_USER and an other for /api/internal/ allowed for ROLE_ADMIN
but behind, this is the same API ?

If I create two applications, I must duplicate the entities and it's not the goal

**Comment by dunglas** [comment]
Yes it's the same API for each endpoint is fully isolated.
If you want to expose less details as possible about your API, you can also put /api (the endpoint) and /api/apidoc under a firewall.
