### ISSUE TITLE
Projects using API Plaform/ApiBundle

### ISSUE THREAD

**Issue by dunglas** [dunglas/DunglasApiBundle#262]
Hi everybody,

We will launch the API Platform website soon and it will include logos of some companies and projects using API Platform. If you use the project want your logo on the website, let me know!

**Comment by theofidry** [comment]
[in6pio](https://github.com/in6pio/Incipio/Incipio) will as soon as we have a good one ;)

**Comment by felicitus** [comment]
You can include [PartKeepr](https://www.partkeepr.org/). I'll send you a vector logo by mail.
