### ISSUE TITLE
Better autoloading

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#263]
The current behaviour is to add all the source files to the autoload:

```json
"autoload": {
    "psr-4": { "Dunglas\\ApiBundle\\": "" }
}
```

This include the source code for the tests. To fix that, we can move all the source code in a `src` folder and keep the tests in a `tests` folder. Then in the `composer.json`:

```json
"autoload": {
    "psr-4": { "Dunglas\\ApiBundle\\": "src" }
},
"autoload-dev": {
    "psr-4": { "Dunglas\\ApiBundle\\Tests\\": "tests" }
}
```

Now is not the time to fix that as it will break all the PRs, but it should be doable when we'll move the bundle to `api-platform`.

**Comment by dupuchba** [comment]
:+1: agree, to keep in mind for first release

**Comment by dunglas** [comment]
Agree but I think that it should be down in the standalone library of the v2.0.

**Comment by theofidry** [comment]
Obviously that apply for the standalone library. But are you implying this shouldn't for the bundle too?

**Comment by dunglas** [comment]
I prefer to keep with the standard Symfony bundle directory structure for the bundle.
