### ISSUE TITLE
Non-existant properties cause PHP error

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#264]
Hi,

by accident I've set a property on my JSON-LD string in a PUT operation which doesn't exist in my entity. Rather than generating an exception, I receive the following error:

`Error: Call to a member function isCollection() on null`

The root cause is in [AttributeMetadataFactory.php](https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/Factory/AttributeMetadataFactory.php#L57) where the type property is null. I guess the return value should be checked in [ItemNormalizer.php](https://github.com/dunglas/DunglasApiBundle/blob/6e21fdb447d9dadbefc5d8fcdc46fe4669315627/JsonLd/Serializer/ItemNormalizer.php#L145) and throw an exception if the property doesn't exist.

However, there should be a configuration option which allows the developer to ignore non-existant properties.

**Comment by soyuka** [comment]
Related issue about the same error #257

**Comment by dunglas** [comment]
The default behavior must be be to ignore all non-existent attributes. This error should not be thrown. Do you guys have a patch to fix it?

**Comment by felicitus** [comment]
I have a very crude "fix": Simply check if `$type !== null` in both if blocks, so that if `$type` is null the final call within denormalize is `$this->setValue($object, $attributeName, $attributeValue);`.

**Comment by dunglas** [comment]
What's the line throwing the exception? https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/Factory/AttributeMetadataFactory.php#L72 ?

**Comment by felicitus** [comment]
No, the line causing the exception is https://github.com/dunglas/DunglasApiBundle/blob/6e21fdb447d9dadbefc5d8fcdc46fe4669315627/JsonLd/Serializer/ItemNormalizer.php#L244 and https://github.com/dunglas/DunglasApiBundle/blob/6e21fdb447d9dadbefc5d8fcdc46fe4669315627/JsonLd/Serializer/ItemNormalizer.php#L265 - in both cases `$type` is `null`.

**Comment by dunglas** [comment]
Ok. Your fix proposal looks good to me.

**Comment by soyuka** [comment]
As I wrote in #257:

> Error origin: [ItemNormalizer#denormalize](https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/ItemNormalizer.php#L244). Note that, compared to the `normalize` function, there is no test for `!$type`. (L244)

**Comment by dunglas** [comment]
Yes you're right @soyuka. Will someone work on a fix?

**Comment by soyuka** [comment]
The real question is : Might `$type` be null while denormalizing?

**Comment by dunglas** [comment]
Yes for non-existing properties it's a normal behavior IMO.

**Comment by soyuka** [comment]
I can work on a fix next week.

**Comment by dunglas** [comment]
:+1:

**Comment by soyuka** [comment]
In your opinion, should the fix apply to denormalize only?

**Comment by felicitus** [comment]
@soyuka I think so, I haven't noticed any issues with normalize

**Comment by dunglas** [comment]
Yes normalize cannot be affected.

**Comment by soyuka** [comment]
Any idea on how I might be able to test this? 

Thanks.

**Comment by dunglas** [comment]
@felicitus what version do you use because the bug seems to be fixed in 1.0 thanks to the `isset` call.

**Comment by dunglas** [comment]
https://github.com/dunglas/DunglasApiBundle/blob/1.0/JsonLd/Serializer/ItemNormalizer.php#L235

**Comment by soyuka** [comment]
@dunglas I don't think that a `null` type should be valid, because if it is, values could be ignored if you made a typo in your entity declaration.

**Comment by felicitus** [comment]
@dunglas I'm running dev-master from a few days ago

**Comment by dunglas** [comment]
Can you try this fix please? https://github.com/dunglas/DunglasApiBundle/pull/271

**Comment by felicitus** [comment]
I can confirm that the fix works for me.
