### ISSUE TITLE
RFC - Add API Platform org. to Slack

### ISSUE THREAD

**Issue by dupuchba** [dunglas/DunglasApiBundle#278]
I found it really useful for some open source project to add #Slack account.

It promotes communication and knowledge sharing.

What do you think ?

**Comment by theofidry** [comment]
There's also [Gitter](https://gitter.im/) that's quite popular. But would be a good thing :+1:

**Comment by ogizanagi** [comment]
Gitter would be nice :+1:

**Comment by dupuchba** [comment]
@dunglas what do you think ?

**Comment by dunglas** [comment]
Slack and Gitter are both fine for me!

**Comment by dupuchba** [comment]
OK, let's vote:
:+1: for #slack
@ogizanagi :+1: for Gitter

**Comment by sroze** [comment]
:+1: for the both.

**Comment by dupuchba** [comment]
wether we add Slack/Gitter, @dunglas you'll have to create the account as you need rights for that :-)

**Comment by lucascherifi** [comment]
:+1: for slack !

**Comment by dunglas** [comment]
Here we go: https://api-platform.slack.com/

**Comment by dupuchba** [comment]
:+1:

**Comment by dupuchba** [comment]
@dunglas can't connect though, is it open to everyone ?

**Comment by ogizanagi** [comment]
AFAIK it cannot be open to everyone, only by domain or on invitation. That's certainly why Gitter would have been better :stuck_out_tongue:

**Comment by dupuchba** [comment]
@ogizanagi noooo !!! you might be true lol e.g => http://www.reactiflux.com you must ask an invitation :(.

**Comment by dunglas** [comment]
So here is the Gitter room: https://gitter.im/api-platform/api-platform
