### ISSUE TITLE
Composite identifiers don't work

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#282]
Hi,

I have an entity which uses composite identifiers:

```
class UserPreference
{
    /**
     * Defines the key of the user preference
     * @ORM\Column(type="string",length=255)
     * @ORM\Id
     *
     * @Groups({"default"})
     *
     * @var string
     */
    private $preferenceKey;

    /**
     * Defines the value. Note that the value is internally stored as a serialized string.
     *
     * @ORM\Column(type="text")
     *
     * @Groups({"default"})
     * 
     * @var mixed
     */
    private $preferenceValue;

    /**
     * Defines the user
     * @ORM\ManyToOne(targetEntity="PartKeepr\AuthBundle\Entity\User")
     *
     * @ORM\Id
     * @var \PartKeepr\AuthBundle\Entity\User
     */
    private $user;
```

When attempting to use it, I receive the following error:

```
The class \PartKeepr\AuthBundle\Entity\\UserPreference has no identifier.
```

I assume that it's hard to implement composite identifiers, so I propose to change the exception message to reflect that, something like "Composite identifiers detected, unable to use".

**Comment by dunglas** [comment]
It's a design choice to not allow composite id. A workaround is to add a custom method like the following:

```php
public function getId()
{
    return $referenceKey.'-'.$user;
}
```

You'll also need a custom `DataProvider`.

The error message looks good to me because it can be thrown when an entity has no identifier at all.

**Comment by ogizanagi** [comment]
Using the `dev-master`, we used an item query extension in order to achieve this at the `DataProvider` level.

**Comment by felicitus** [comment]
@dunglas Unfortunately the message did not shed any light for me. Identifier is a pretty generic term and the first thing I did was looking in my entity if it had an identifier, and yes it had. So I read the code in the ApiBundle, which usually shouldn't be necessary. Maybe this message would clear confusion:

 "The class \PartKeepr\AuthBundle\Entity\\UserPreference has no identifier. Maybe you forgot to define the Identifier, or using composite identifiers?"

Also, I think it should be documented, if not done already.

**Comment by dunglas** [comment]
:+1: for your new message.

**Comment by soyuka** [comment]
Is there a reason why composite identifiers are not supported?

**Comment by Soullivaneuh** [comment]
> Actually by providing a DataProvider it works just fine :).

Maybe could you add a sample here? :-)

**Comment by jdevinemt** [comment]
@soullivaneuh 
> Maybe could you add a sample here? :-)

Here's an example of how to write an endpoint to retrieve items based on a Doctrine entity that uses a composite key.

```php
// src/Entity/Composite.php

#[ApiResource]
#[ORM\Entity(repositoryClass: CompositeRepository::class)]
class Composite
{
    #[ApiProperty(identifier: false)]
    #[ORM\Id]
    #[ORM\Column(type: "integer")]
    private $firstId;

    #[ApiProperty(identifier: false)]
    #[ORM\Id]
    #[ORM\Column(type: "integer")]
    private $secondId;

    #[ApiProperty(identifier: true)]
    public function getId(): string
    {
        return $this->firstId.'-'.$this->secondId;
    }

    // ... property getters/setters
}
```

The important part on the entity is that you indicate that the Doctrine ID properties should not be used as identifiers for API Platform. Instead add a method that returns your composite key as a string and mark it to be used as an identifier for API Platform. 

I've used the name `getId()` for retrieving the composite key but you could use `getCompositeId()` or whatever name you'd like. This may be needed in cases where the entity already has an `$id` field or `getId()` method.

```php
// src/Api/DataProvider/CompositeItemDataProvider.php

class CompositeItemDataProvider implements ItemDataProviderInterface, RestrictedDataProviderInterface
{
    private CompositeRepository $compositeRepository;

    public function __construct(CompositeRepository $compositeRepository)
    {
        $this->compositeRepository = $compositeRepository;
    }

    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return $resourceClass === Composite::class;
    }

    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = [])
    {
        list($firstId, $secondId) = explode('-', $id);

        return $this->compositeRepository->findOneBy([
           'firstId' => $firstId,
           'secondId' => $secondId
        ]);
    }
}
```

In the data provider's `getItem()` method we parse the ID provided from our entity's `getId()` method and manually retrieve the appropriate entity from the database. The `supports()` method just indicates that this data provider should only be used for Composite entity resources.

The IRI for a Composite item would then become `/api/composite/{firstId}-{secondId}`
