### ISSUE TITLE
OrderBy-Filter supporting relations

### ISSUE THREAD

**Issue by blaues0cke** [dunglas/DunglasApiBundle#309]
We just wrote a filter that allows you to sort by related table entities using `order[relatedTable.column]=desc`. You can get it here: https://gist.github.com/blaues0cke/6f1a53e1bd5d9dda8974

Should be place a pull request for this?

**Comment by vincentchalamon** [comment]
Please have a look at this one: https://github.com/dunglas/DunglasApiBundle/pull/242

**Comment by theofidry** [comment]
Feature added in 1.1 (still in beta) :)
