### ISSUE TITLE
Rename the bundle

### ISSUE THREAD

**Issue by dunglas** [dunglas/DunglasApiBundle#31]
As the core of the bundle is now independent of JSON-LD and Hydra (it's possible to add HAL or any other serialization format support), what do you think about renaming the bundle "ApiBundle"?

**Comment by theofidry** [comment]
I think the question was more addressed to @sroze but I'll put in my's two penn'orth: it would make more sense indeed, as long as it is well referenced. I remember the first time I had to look for your bundle I and a colleague were given the wrong name (just "JsonLdBundle"), and we did not find it...

**Comment by dunglas** [comment]
Your feedback is welcome. This is a question for everyone interested in that bundle :-)
