### ISSUE TITLE
TOC for doc

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#32]
The documentation is becoming quite long so a TOC would be very much appreciated regardeless if the doc is planned to be move elsewhere later!

**Comment by sroze** [comment]
It shouldn't be moved elsewhere than in multiple files in a `doc` repository :)

**Comment by dunglas** [comment]
It's on my todo list !

**Comment by dunglas** [comment]
[ ] Split the documentation into multiple files
[ ] Create the website

**Comment by theofidry** [comment]
Ok, you plan to do it really soon? If not, which would not be surprising the TOC would be a very acceptable temporary solution!

**Comment by dunglas** [comment]
ASAP but it will be a TOC (in `README.md`) pointing to files in `Resources/doc`.

**Comment by theofidry** [comment]
Ok great.
