### ISSUE TITLE
Impossible to add filter in a custom controller

### ISSUE THREAD

**Issue by alexcandy91** [dunglas/DunglasApiBundle#360]
Hello, 
I'm trying to add filters in a custom controller but the initFilter function dosesn't work.
Why I'm using a customerControler?
Because I have 3 need of my application:
1) get item by Number (unique) and not by ID
2) use groups to give some information when you try to get a list and different information when you get a single item
3) filter items by others parameters.

So, if I try to add filters using custom controller the bundle add the filters only to the ItemOperation method and not to the CollectionOperation.

Is this a bug?

this is my service:

      api.service:
                  class: AppBundle\Services\ApiService
                  arguments: ['@service_container']
  
      resource.store.item_operation.store_get:
              class:   "Dunglas\ApiBundle\Api\Operation\Operation"
              public:  false
              factory: [ "@api.operation_factory", "createItemOperation" ]
              arguments:
                  -    "@resource.store"               # Resource
                  -    [ "GET"]                 # Methods
                  -    "/store/{number}"           # Path
                  -    "AppBundle:Store:get"         # Controller
                  -    "store_details"                 # Route name
                  -    # Context (will be present in Hydra documentation)
                       "@type":       "hydra:Operation"
                       "hydra:title": "A custom operation"
                       "returns":     "xmls:string"
  
      resource.store.collection_operation.store_get:
                  class:   "Dunglas\ApiBundle\Api\Operation\Operation"
                  public:  false
                  factory: [ "@api.operation_factory", "createItemOperation" ]
                  arguments:
                      -    "@resource.store"               # Resource
                      -    [ "GET"]                 # Methods
                      -    "/stores"             # Path
                      -    "AppBundle:Store:getList"         # Controller
                      -    "store_list"                 # Route name
                      -    # Context (will be present in Hydra documentation)
                           "@type":       "hydra:Operation"
                           "hydra:title": "A custom operation"
                           "returns":     "xmls:string"
  
      resource.store:
              parent:    "api.resource"
              arguments: [ "AppBundle\Entity\Store" ]
              calls:
                          -      [ "initItemOperations", [ ["@resource.store.collection_operation.store_get"] ] ]
                          -      method:    "initFilters"
                                 arguments: [ [ "@resource.store.search_filter" ] ]
                          -      [ "initCollectionOperations", [ [ "@resource.store.item_operation.store_get"] ] ]
              tags:      [ { name: "api.resource" } ]
  
      resource.store.search_filter:
              parent:    "api.doctrine.orm.search_filter"
              arguments: [ { siteId: "partial", name: "partial"  } ]

This is my customController:
<?php
    
    // src/AppBundle/Controller/CustomController.php
    
    namespace AppBundle\Controller;
    
    use Dunglas\ApiBundle\Controller\ResourceController;
    use Dunglas\ApiBundle\Event\DataEvent;
    use Dunglas\ApiBundle\Event\Events;
    use Symfony\Component\HttpFoundation\Request;
    use Dunglas\ApiBundle\Api\Resource;
    
    class StoreController extends ResourceController
    {
    
        public function getAction(Request $request, $number)
        {
            $em = $this->getDoctrine()->getManager();
            $store = $em->getRepository('AppBundle:Store')->findOneBySiteId($number);
            $groups = ['groups' => ['details']];
            $resource = new Resource('AppBundle\Entity\Store');
            $resource->initNormalizationContext($groups);
            $object = $this->findOrThrowNotFound($resource, $store->getId());
            $this->get('event_dispatcher')->dispatch(Events::RETRIEVE, new DataEvent($resource, $object));
            return $this->getSuccessResponse($resource, $object);
        }
    
        public function getListAction(Request $request)
        {
            $groups = ['groups' => ['list']];
            $resource = new Resource('AppBundle\Entity\Store');
            $resource->initNormalizationContext($groups);
            $data = $this->getCollectionData($resource, $request);
            if (
                $request->get($this->container->getParameter('api.collection.pagination.page_parameter_name')) &&
                0 === count($data)
            ) {
                throw $this->createNotFoundException();
            }
            $this->get('event_dispatcher')->dispatch(Events::RETRIEVE_LIST, new DataEvent($resource, $data));
            return $this->getSuccessResponse($resource, $data, 200, [], ['request_uri' => $request->getRequestUri()]);
        }
    }
I would like to use the bundle because I's better to use the hidra information, the impagination and so on...

Thank you so much for the answers.

Regards

**Comment by alexcandy91** [comment]
This is the result, I have the filter on the single item request and not in the collection.

![image](https://cloud.githubusercontent.com/assets/16149868/11588829/aedd59ec-9a83-11e5-837e-943eccdd21ae.png)

**Comment by ltouro** [comment]
@alexcandy91 it has been a while but i noticed that your resource.store calls have arguments flipped between initItemOperations and initCollectionOperations

**Comment by alexcandy91** [comment]
Yes I already see that.

However, thank you so much!
Regards

**Comment by soyuka** [comment]
This can be closed imo
