### ISSUE TITLE
OrderFilter is excluding Resources without relations

### ISSUE THREAD

**Issue by salahm** [dunglas/DunglasApiBundle#363]
Hi,

There is an issue with the OrderFilter and relations

Use Case : 
i have an Entity `Category` which can have a `parent`. the relation is not mandatory.
when i try to sort the list with, lets say `parent.title`. i'm loosing all my categories which don't have a parent.

Regarding this line : https://github.com/dunglas/DunglasApiBundle/blob/1.x/Doctrine/Orm/Filter/OrderFilter.php#L82

we're using a `join` instead of a `leftJoin`. is there any reason for that choice ? 

ping @vincentchalamon

**Comment by dunglas** [comment]
Yes it should be a left join.

**Comment by dunglas** [comment]
ping @teohhanhui

**Comment by teohhanhui** [comment]
Agreed. It's a problem. But do we need "null management" (like in `DateFilter`) for this?

**Comment by dunglas** [comment]
IMO a left join is enough? Can anyone work on a PR?

**Comment by vincentchalamon** [comment]
I'm on it: https://github.com/dunglas/DunglasApiBundle/pull/367
