### ISSUE TITLE
Attempted to load class "SetterExtractor" 

### ISSUE THREAD

**Issue by yelmontaser** [dunglas/DunglasApiBundle#377]
bug related to the new release http://www.github.com/dunglas/php-property-info/tree/v0.2.2.

```PropertyInfo\Extractors\SetterExtractor``` was deleted.

**Comment by manukn** [comment]
Attempted to load class "SetterExtractor" from namespace "PropertyInfo\Extractors".
Did you forget a "use" statement for another namespace? 
Anyway to solve this problem?

**Comment by dunglas** [comment]
I've just tagged a new release fixing this problem. Run `composer update`. Sorry for the inconvenience.

**Comment by yelmontaser** [comment]
@dunglas thanks.
