### ISSUE TITLE
FosUserBundle bug in PUT action

### ISSUE THREAD

**Issue by marcin-piela** [dunglas/DunglasApiBundle#381]
I have the same problem like in this closed issue: https://github.com/dunglas/DunglasApiBundle/issues/55

I installed FosOAuthServerBundle and made FosUser integration with ApiBundle, and now I have that situation:
- Make request for OAuth token with grant_type password (admin user)
- Make Put request for Users/1 (Admin) with Authorization Token (I’m logged as Admin user with this token)
- Response is like the User Entity is **empty** so there are a validation errors like empty email and username.

I Found that the Class of User Entity from **„findOrThrowNotFound”** method is:
**"Proxies\__CG__\AppBundle\Entity\Profile\User"**

But in „deserialize” method in PutAction we send class parameter:
**„AppBundle\Entity\Profile\User”** - so in ItemNormalizer class we have variable „overrideClass” with false and object cannot be initialize cause it expecting class **„AppBundle\Entity\Profile\User”** not proxy class.

If I make request for another User (not logged) or when I’m using token with grant_type client_credentials everything is ok. 
**How fix that?**

Thanks

**Comment by dunglas** [comment]
Can you post the full stack trace here please?

**Comment by dunglas** [comment]
If the `object_to_populate` key exists and is associated with an instance of the proxy, it should work as expected.
Can you provide a failing test?

**Comment by dunglas** [comment]
Ok, it looks like the problem is in Symfony directly.

https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractNormalizer.php#L264

Can you try to replace `$class === get_class($context['object_to_populate'])` with `$context['object_to_populate'] instanceof $class === get_class()`?
If it fixes your problem I'll open a PR against Symfony.

**Comment by marcin-piela** [comment]
It will be ok if I replace with:
     
     $context['object_to_populate'] instanceof $class

**Comment by marcin-piela** [comment]
https://github.com/symfony/symfony/issues/15627

**Comment by marcin-piela** [comment]
Thanks
