### ISSUE TITLE
Question: SerializationGroups per Action

### ISSUE THREAD

**Issue by felicitus** [dunglas/DunglasApiBundle#383]
I'm trying to implement a feature where a collection should be able to be written in a `POST` request but not in `PUT` requests. Something like:

`Groups{"default", "stock"}` for `POST` and `Groups{"default"}` for `PUT`.

Is it possible to implement that using the current DunglasApiBundle?

**Comment by dunglas** [comment]
It will be possible when #375 will be finished (it's one of the goals of this PR).

**Comment by soyuka** [comment]
+1 I think it's part of v2, different serialization groups per methods
Le lun. 11 janv. 2016 à 13:53, Timo A. Hummel <notifications@github.com> a
écrit :

**Comment by felicitus** [comment]
Perfect! I'll close the issue and watch #375
