### ISSUE TITLE
How to add user security through custom UserDataProvider

### ISSUE THREAD

**Issue by vincentchalamon** [dunglas/DunglasApiBundle#395]
The following story: _as a user, I shouldn't be able to update another user_.

So, I think I should add a custom `UserDataProvider` which extends default `DataProvider`, and supports my user class. On this one, I override `getItem` method and compare requested user with authenticated user: if they're identical, I should return the requested user, otherwise I should return `null`.

But because of `DataProviderChain::getItem` method, if `UserDataProvider` returns null, it will continue to the default `DataProvider` which will return the requested user (but it shouldn't).

Shouldn't `DataProviderChain::getItem` method be like following ?:
```php
public function getItem(ResourceInterface $resource, $id, $fetchData = false)
{
    foreach ($this->dataProviders as $dataProvider) {
        if ($dataProvider->supports($resource)) {
            return $dataProvider->getItem($resource, $id, $fetchData);
        }
    }
}
```

Or is there a better way to manage this story (for example) ?

**Comment by soyuka** [comment]
In my opinion this request should not hit the DataProvider. In my case, I use Voters to prevent such security issues, if the user has no rights on a Resource the request will throw an AccessDeniedException before it gets to the api-bundle listeners.

**Comment by vincentchalamon** [comment]
Actually, in version 1.*, I think api-platform does not use voters in its controller. Maybe should it be a good idea to implement it ?

**Comment by dunglas** [comment]
Voters can be called in events: https://api-platform.com/doc/1.0/api-bundle/the-event-system#updating-item

**Comment by soyuka** [comment]
For example, this is my `PermissionListener`:

```
<?php

namespace Core\SecurityBundle\EventListener;

use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\HttpKernel\Event\FilterControllerEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

use Core\SecurityBundle\Security\ResourcePermissions;
use Symfony\Component\HttpKernel\KernelInterface;

class PermissionListener implements EventSubscriberInterface
{
    /** @var Core\ApiBundle\Security\ResourcePermissions **/
    private $resourcePermissions;

    public function __construct(ResourcePermissions $resourcePermissions, KernelInterface $kernel)
    {
        $this->resourcePermissions = $resourcePermissions;
        $this->kernel = $kernel;
    }

    public function onKernelController(FilterControllerEvent $event)
    {
        if($this->kernel->getEnvironment() === 'test') {
            return; 
        }

        $request = $event->getRequest();

        if (!$request->attributes->has('_resource')) {
            return;
        }

        if(!$this->resourcePermissions->isGranted($request)) {
            throw new AccessDeniedException("ACL permission on this object is not granted.");
        }
    }

    public static function getSubscribedEvents()
    {
        return array(
            KernelEvents::CONTROLLER => 'onKernelController',
        );
    }
}
```

The `resourcePermissions` is a kind of ACL based on the `resourceCollection`.

I don't think that it's a good idea to implement this in the api-bundle, lot of overhead for something that can be very application-specific.

**Comment by vincentchalamon** [comment]
:+1: thanks guys, I'll implement it on that way :)

**Comment by dunglas** [comment]
:+1: @soyuka 

Is someone interested to add a doc entry about that? It can help a lot of people!

**Comment by soyuka** [comment]
I'm on it, may I add a new section on the docs? 

For example: 
> 15. Security through voters

Or you had a section in mind where this should go? 

@vincentchalamon if you want the full example, I can publish my security bundle on github.

**Comment by vincentchalamon** [comment]
@soyuka should be OK, I'm working on it from your PermissionListener. Thanks

**Comment by jordanaubert** [comment]
@dunglas but what about `putAction` & `postAction` in ResourceController ? API events will be Events::PRE_UPDATE (for `putAction` for example), but at this event resource is already modified (but not persisted). Is there any retrieve event for put & post to denied access only for those methods ?

In my case, I want to restrict access get & put actions on my current user (get will be managed using `api.retrieve` event, but what about put ?)

**Comment by soyuka** [comment]
@jordanaubert seems more complicated then having a voter that does it for you, if you take the PermissionListener above, you just have to check request methods. For example:

```
<?php
namespace Core\SecurityBundle\Security;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Acl\Domain\ObjectIdentity;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

class ResourcePermissions
{
    /** @var Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface **/
    private $authorizationChecker;

    const ACL_METHODS = [
        'GET' => 'VIEW',
        'POST' => 'CREATE',
        'PUT' => 'EDIT',
        'DELETE' => 'DELETE'
    ];

    public function __construct(AuthorizationCheckerInterface $authorizationChecker)
    {
        $this->authorizationChecker = $authorizationChecker;
    }

    public function isGranted(Request $request) {
        if (!$this->authorizationChecker->isGranted('IS_AUTHENTICATED_FULLY')) {
            throw new AccessDeniedException("User is not fully authenticated");
        }

        return $this->authorizationChecker->isGranted(
            self::ACL_METHODS[$request->getMethod()],
            new ObjectIdentity($request->attributes->get('_resource'), 'resource')
        );
    }
}
``` 

Here you'd have a Voter that supports this kind of ObjectIdentity and you're good to go.

**Comment by vincentchalamon** [comment]
@soyuka :+1:

**Comment by PierrePX** [comment]
Hello.

First of all : beau travail ! very good job with this framework!

I'm using ApiPlatform 2.1 and I'm having some issues with security and dataproviders.

I added ACL in my entity annotations: 
`* @ApiResource(
 *  iri="http://schema.org/Organization",
 *  attributes={
 *      "access_control"="is_granted('ROLE_USER')",
 *      "normalization_context"={"groups"={"chrome-ext"}}
 *  },`

And I'm using a custom itemdataprovider to fetch my entity.
The problem is that I need my user entity in the dataprovider, to check if the client is authorized to fetch the resource.

`public function getItem(string $resourceClass, $id, string $operationName = null, array $context = [])
    {
        $this->user->checkSocieteAuthorized($id);
        // Some more stuff...
`

My problem is that the ACL is done after fetching data through the dataprovider. So i can't guarantee to have a logged user inside my dataprovider.

What would be the best way to handle this?

Thanks in advance
