### ISSUE TITLE
[Question] Validation through json schemas

### ISSUE THREAD

**Issue by soyuka** [dunglas/DunglasApiBundle#402]
I was thinking about validation constraints, and as we're playing a lot with json in this library I thought it would be nice to validate data through json schemas. I don't think that Annotations are good for entities validation in a system which may change, or be used in a different way. Yaml validations would be sufficient, but json-schema's are more portable and might be re-used for a different task.

I've started an implementation which:
- takes a Class constraint  annotation (specifying, or not, the json schema)
- parse the schema through [justinrainbow/json-schema](https://github.com/justinrainbow/json-schema)
- checks input data through the `json-schema` validator

Now, I hit a wall where `json-schema` does not accept Classes, but requires an object. Which leads to three solutions:
- try to validate input data before the denormalization - as a side-effect, it'll not be possible to only send one property to update the whole object will be needed
- serialize the Entity to valid it through the shema - this would be the cleaner solution, but the entity will be serialized twice (validation + response)
- try to hack into the `json-schema` validator to accept Classes - this could definitly work but will require more work

What would be your choice if you had to implement this? Would you have a solution in mind that I haven't think about? Or is this maybe a bad idea?

**Comment by dunglas** [comment]
I make a longer reply another day because I'm working on the same topics but https://github.com/dunglas/php-to-json-schema and https://github.com/symfony/symfony/pull/17660 can be interesting for your search.

**Comment by soyuka** [comment]
Thanks, will definitely study this. I'd love to hear your thoughts on the subject!

**Comment by soyuka** [comment]
Update:

I've used the symfony property accessor [here](https://github.com/justinrainbow/json-schema/blob/master/src/JsonSchema/Constraints/ObjectConstraint.php#L141) so that properties are correctly fetched from entities as well as standard objects. It works fine for now (hacked in a hurry) but I'll have to dig a bit more into json schema's to see if there are no caveats using this solution. 
If this works fine I'm thinking about opening a PR on `justinrainbow/json-schema` to implement this usage.

Just for the record, I'm using symfony validators with [this json-schema bundle](https://github.com/HadesArchitect/JsonSchemaBundle). For those who are interested, [this is the current implementation](https://gist.github.com/soyuka/b4da5f51c26e6d01c631). Of course it won't work from scratch as `json-schema` does not read properties through accessors (yet :)).

**Comment by dunglas** [comment]
I've just opened a PR for the Symfony Property Accessor that can help dealing with such cases: https://github.com/symfony/symfony/pull/17738

**Comment by soyuka** [comment]
I'm not facing any issue with types here so I don't really get the relation between your PR and the json schema study case. 
Anyway, `justinrainbow/json-schema` doesn't use the Symfony Property Accessor yet.

**Comment by dunglas** [comment]
The problem is when the submitted JSON contain something like `{"date": "foo"}` and the setter is like `setDate(\DateTimeInterface $d)` but maybe it's not applicable to what you're doing now.

**Comment by soyuka** [comment]
Indeed, that's what I understood from the previous PR too. 
Here `justinrainbow/json-schema` reads the json-schema, then it just reads the normalized entity and checks if it's valid according to the schema's informations. If it fails, validation errors are thrown, if not the entity is persisted.

Basically I've fixed my issue, I'm doing a clean implementation tomorrow.

**Comment by soyuka** [comment]
I'm closing this one because it's not really in the dunglas/api-bundle scope. I started a small implementation of a bundle that helps managing json-schema files (generation, validation): https://github.com/soyuka/JsonSchemaBundle.
I'm using the `dunglas/php-to-json-schema` to parse php files and made my own generator to work with Doctrine entities.
