### ISSUE TITLE
[ Question ] Many to many Serialization 

### ISSUE THREAD

**Issue by MajdiJ** [dunglas/DunglasApiBundle#411]
Hello everyone , I've just started working with this bundle (v1.1.0) . I'm following the documentation and encountred a problem in the serialization .
This is [the project](https://github.com/MajdiJ/test_dunglas_api) i'm working on .
I have a many to many relation between the bus and driver entities.
When I try to add a bus with a list of drivers or just one driver I have no errors but the POST request doesn't persist the driver (association table is empty).
Can you help me plz :) ?

**Comment by yelmontaser** [comment]
Is that the relationship has the property ```@ORM\ManyToMany(..., cascade={"persist"})"```

**Comment by MajdiJ** [comment]
I tried with @ORM\ManyToMany(..., cascade={"persist"})" and even @ORM\ManyToMany(..., cascade={"all"})"
It's like the request is not considering the drivers[] data i'm giving .

**Comment by 3kynox** [comment]
Sounds related to problem I have in #403. Adding abstract class case error returned I have too.

**Comment by MajdiJ** [comment]
I'm using two simple classes with only manyTomany relation between the two ; all i want to do is to be able to add a bus with a list of drivers in the POST request ; do you think I added the @groups in the wrong place ?

**Comment by yelmontaser** [comment]
The Drivers well created but without name :

POST
```json
{
  "brand": "Man",
  "driver": [
    {"name": "Jean Smith"},
    {"name": "Bob Foo"}
  ]
}
```
Response :
```json
{
  "@context": "/api/contexts/Bus",
  "@id": "/api/buses/5",
  "@type": "Bus",
  "driver": [
    {
      "@id": "/api/drivers/7",
      "@type": "Driver",
      "name": null
    },
    {
      "@id": "/api/drivers/8",
      "@type": "Driver",
      "name": null
    }
  ],
  "brand": "Man"
}
```
The problem is that you did not apply the deserialization group for the property ```name``` of  Driver.

```php
    /**
     * @var string The name of the driver.
     * 
     * @ORM\Column(nullable=true)
     * @Assert\Type(type="string")
     * @Groups({"bus_read"})
     */
    private $name;
```
Should be it:
```php 
@Groups({"bus_read", "bus_write"})
```

**Comment by MajdiJ** [comment]
I tried doing that and got this error : 
Nested objects for attribute "driver" of "AppBundle\Entity\Bus" are not enabled. Use serialization groups to change that behavior. These are my services :


        resource.driver:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Driver" ]
        tags:      [ { name: "api.resource" } ]
         
        resource.bus:
        parent:    "api.resource"
        arguments: [ "AppBundle\\Entity\\Bus" ]
        calls:
            -      method:    "initNormalizationContext"
                   arguments: [ { groups: [ "bus_read" ] } ]
            -       method:    "initDenormalizationContext"
                    arguments:
                        -      { groups: [ "bus_write" ] }
        tags:      [ { name: "api.resource" } ]

         
Am I calling the services the right way ? (I'm new to all of this sorry )

**Comment by yelmontaser** [comment]
I tried https://github.com/MajdiJ/test_dunglas_api/tree/master and it works as expected.

**Comment by MajdiJ** [comment]
Thank you @yelmontaser !

**Comment by MajdiJ** [comment]
I configured the relation in the bus entity with 
*@ORM\ManyToMany(targetEntity="Driver", mappedBy="bus",cascade={"persist","remove","merge"})
The drivers indeed are added to the database with that request but the table buses_drivers is still empty.
Also if the driver already exists it adds a duplication.
Is it a normal behavior or should I make further configuration ?

**Comment by jayesbe** [comment]
@MajdiJ  When it wasn't working for you.. were you on v1.0 branch ?  Im getting the same issue though with a OneToOne mapping.  I haven't tried the master branch as it says its experimental at the moment and not ready for production.

**Comment by MajdiJ** [comment]
@jayesbe Yes and my problem was solved on the v1.0 too . What kind of problem are you having ?

**Comment by jayesbe** [comment]
I have the following object 

```
{ '@context': '/app_dev.php/api/contexts/User',
  '@id': '/app_dev.php/api/users/30767',
  '@type': 'User',
 profile: 
         { '@id': '/app_dev.php/api/user_profiles/30767',
         '@type': 'UserProfile',
         height: 180,
         profileImage: 
                { '@id': '/app_dev.php/api/me/match/media/355',
                  '@type': 'Media'
                }
         }
```

I am trying to change the profileImage from id 355 to id 354

when I execute the PUT

I get 
```
'PUT ERROR', { '@context': '/app_dev.php/api/contexts/Error',
                                                                                    '@type': 'Error',
                                                                                    'hydra:title': 'An error occurred',
                                                                                    'hydra:description': 'Nested objects for attribute "profileImage" of "App\\UserBundle\\Entity\\UserProfile" are not enabled. Use serialization groups to change that behavior.',
                                                                                    trace: 
```

the User object and UserProfile object is a OneToOne via profile
likewise the Media object is a OneToOne to UserProfile via profileImage

User.php
```
    /**
     * @var UserProfile $profile
     *
     * @ORM\OneToOne(targetEntity="UserProfile", mappedBy="user", fetch="LAZY", cascade={"persist"})
     * @Assert\Valid
     * @Groups({"api_read","api_write"})
     */
    private $profile;
```

UserProfile.php
```
    /**
     *
     * @ORM\OneToOne(targetEntity="App\MediaBundle\Entity\Media", cascade={"persist"}, fetch="LAZY")
     * @ORM\JoinColumn(name="profile_image_id", referencedColumnName="id", onDelete="SET NULL")
     * @Groups({"api_read","api_write"})
     */
    private $profileImage;

```

**Comment by MajdiJ** [comment]
This is what worked for me 
```

/**
     *@var ArrayCollection<Driver> The driver of this bus.
     *@ORM\ManyToMany(targetEntity="Driver", mappedBy="bus",cascade={"persist","remove","merge"})
     *@ORM\JoinColumn(name="DRIVER_id", referencedColumnName="id")
     *@Groups({"bus_write"})
     */
     
    private $driver;

/**
     * @var ArrayCollection<Bus> The buses of this driver
     * @ORM\ManyToMany(targetEntity="Bus", inversedBy="driver",cascade={"persist","remove","merge"})
     * @ORM\JoinTable(name="bus_driver")
     * @Groups({"bus_write,bus_read"})
     */
    private $bus;
```

**Comment by jayesbe** [comment]
I changed

```
    /**
     * @var UserProfile $profile
     *
     * @ORM\OneToOne(targetEntity="UserProfile", mappedBy="user", fetch="LAZY", cascade={"persist"})
     * @Assert\Valid
     * @Groups({"api_read","api_write"})
     */
    private $profile;
```

to 

```
    /**
     * @var UserProfile $profile
     *
     * @ORM\OneToOne(targetEntity="UserProfile", mappedBy="user", fetch="LAZY", cascade={"persist"})
     * @Assert\Valid
     * @Groups({"api_read, api_write"})
     */
    private $profile;
```

however now documentation doesnt generator correctly. I'll try placing api_write first.. but some how I really doubt that will change anything.

**Comment by jayesbe** [comment]
I found my issue. I was not assigning the property an IRI but an object.  The API was expecting just the IRI

**Comment by teohhanhui** [comment]
@jayesbe See https://api-platform.com/doc/1.0/api-bundle/serialization-groups-and-relations#embedding-relations
