### ISSUE TITLE
Invalid property for filter behavior

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#42]
As of now, if we filter a collection on a not enabled property, the collection will be returned as a whole as if no filter is given. bIMO it is error prone in a sense that you have no way to tell there is an error occurred unless you take a look at the result.

Would it be possible to change that or it's a desired behavior?

**Comment by dunglas** [comment]
Quote of https://github.com/dunglas/DunglasApiBundle/pull/43#issuecomment-98353716:
> It was a voluntary choice to ignore to ignore invalid query parameters for reasons similar of those explained here: http://stackoverflow.com/questions/15947074/extra-query-parameters-in-the-rest-api-url
But I've no strong opinion about that. I think it's more confortable and less error prone to ignore invalid parameters (think the tons of client side tools such as Google Analytics that append custom parameters to URLs).
