### ISSUE TITLE
Roles limitation

### ISSUE THREAD

**Issue by 3kynox** [dunglas/DunglasApiBundle#430]
Hello,

If I want to limit a specific action (CREATE/POST action of specific exposed entity) for a given Symfony user role, what could be the best way to achieve this ?

Using security.yml file, I know how to limit an /URI to a role, but not specific methods.

ps: using FOSUser too.

**Comment by soyuka** [comment]
It works well with voters (see #395)
#182 related

**Comment by 3kynox** [comment]
Thanks, I'll test this.
