### ISSUE TITLE
Embedded resources

### ISSUE THREAD

**Issue by Sorendil** [dunglas/DunglasApiBundle#432]
Hello,

I'd like to have "Embedded resources". By this term, I mean that a Resource B is directly dependant and embedded into another resource A.

For example if articles have comments, I'd like to have 
RESOURCE A : /articles/1
RESOURCE B : /articles/1/comments

instead of

RESOURCE A : /articles/1
RESOURCE B : /comments/XXX

As you see, comments can't existe without a parent resource.

I don't see anything in the doc that enables doing this.

According to you, what is the best way to implement this ?

**Comment by dunglas** [comment]
Are you using the v1 or the v2 (master branch)?

**Comment by Sorendil** [comment]
V1,

Since you ask, I guess that it will be allowed in V2 ?

I can't see any doc for the V2, I guess it's not wrote yet ?

**Comment by dunglas** [comment]
You're right about the doc. It will be easier in v2 but it's already doable in v1.
You can customize URL using the operation factory: https://api-platform.com/doc/1.0/api-bundle/operations#creating-custom-operations

Then you can make the bundle generate correct "sub URLs" by implementing the [IriConverterInterface](https://github.com/dunglas/DunglasApiBundle/blob/1.x/Api/IriConverterInterface.php) (usually decorating the default implementation) and replacing the `api.iri_converter` service (usually [using service decoration](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services).

However it's some work and IMO it doesn't have any benefit over using "root" URLs and validations rules such as "the comment must be related to a post".

**Comment by Sorendil** [comment]
Well, thank you for responding fastly !

Ok, thanks for detailed response !

Yes, for comments it could be avoided but it's very useful because you can't access comments if you can't access articles. But I have other resources where it will be more useful that comments.

Since it's possible, I'm going to migrate to DunglasAPI v1 and v2 when it'll be available. Thank you for all your work !

Sorendil.
