### ISSUE TITLE
[ Question ] Raw json configuration 

### ISSUE THREAD

**Issue by MajdiJ** [dunglas/DunglasApiBundle#435]
Hello , what configuration should I make to have a raw json response like this
 
`[ { "id": 1, "name": "Player 1" } ]`

instead of the json-ld/hydra response 

`{"@context":"\/api\/contexts\/Player","@id":"\/api\/players","@type":"hydra:PagedCollection","hydra:totalItems":1,"hydra:itemsPerPage":30,"hydra:firstPage":"\/api\/players","hydra:lastPage":"\/api\/players","hydra:member":[{"@id":"\/api\/players\/1","@type":"Player","team":null}]}`

**Comment by soyuka** [comment]
You'd have to add a custom controller and return your own `Response` object. I don't see the point of using this library without json-ld though.

**Comment by MajdiJ** [comment]
The purpose of what i do right now is experimenting this api on various project .
Maybe it's better to treat the json answer client side is a better option .
