### ISSUE TITLE
Fos User and Post Data

### ISSUE THREAD

**Issue by blump** [dunglas/DunglasApiBundle#50]
Hello, 

Sorry for my english, I'm French .... 

After configuring and FOS FOS BUNDLE USER AUTH USER. I have no problem with but with a GET on HOST POST / api / books for example , I have this error:

<pre>hydra:description": "Catchable Fatal Error: Argument 1 passed to Dunglas\\ApiBundle\\FosUser\\EventSubscriber::__construct() must implement interface Symfony\\Component\\EventDispatcher\\EventDispatcherInterface, none given, called in /var/www/local.dev/XXXX/api-platform/app/cache/prod/appProdProjectContainer.php on line 331 and defined"</pre>

thank you for your answers

**Comment by dunglas** [comment]
This is a bug in the bundle.
Parameters are not injected properly: https://github.com/dunglas/DunglasApiBundle/blob/master/Resources/config/fos_user.xml#L8

I'll fix ASAP but fell free to open a PR if you have the time to do it.

**Comment by blump** [comment]
Ah ok ! Missing 
<pre>
<argument type="service" id="event_dispatcher" />
 <argument type="service" id="fos_user.user_manager" />
</pre> 
no ? 

By the way thank you for your work

**Comment by dunglas** [comment]
yes!

**Comment by dunglas** [comment]
Closed by #51.
