### ISSUE TITLE
PUT my object user (Fos user) not work

### ISSUE THREAD

**Issue by blump** [dunglas/DunglasApiBundle#55]
Hello,
When I made ​​a PUT request on my user id identified with FOS Oauth SERVER BUNDLE and FOS USER , I am instead a POST because it does not retrieve the user object.

If I want to update the User object different from mine , no problem

Here the User with id 3 with the token that begins with MWQ1 ....

PUT on api/v1/users/ 2 it's work
PUT on api/v1/users/ 3 not work

![capture d ecran 2015-05-08 a 11 54 18](https://cloud.githubusercontent.com/assets/10714122/7534481/395dcb8c-f57b-11e4-99df-76c2ccd9d932.png)
![capture d ecran 2015-05-08 a 11 54 41](https://cloud.githubusercontent.com/assets/10714122/7534482/3d637646-f57b-11e4-9bf3-e190a9cce117.png)

Here the User with id 2 with the token that begins with NTU1 ....

PUT on api/v1/users/3 it's work
PUT on api/v1/users/2 not work

![capture d ecran 2015-05-08 a 11 55 37](https://cloud.githubusercontent.com/assets/10714122/7534510/711d66d6-f57b-11e4-8a19-3f9c200bcb36.png)
![capture d ecran 2015-05-08 a 11 55 19](https://cloud.githubusercontent.com/assets/10714122/7534513/7707e2ec-f57b-11e4-9cb7-5d82209ca5b5.png)

In Dunglas\ApiBundle\FosUser\EventSubscriber.php

<pre>
public function updateObject(ObjectEvent $event)
    {
        $object = $event->getObject();
        if ($object instanceof UserInterface) {
            $this->userManager->updateUser($object);
            $this->eventDispatcher->dispatch(Events::POST_UPDATE, $event);
            $event->stopPropagation();
        }
    }
</pre>

$object is null for the user who wants to change their own user object but correct for the user object of another user.. 

I do not know if I explained the problem ...

Blump

**Comment by dunglas** [comment]
The error seems not related with the bundle (SQL error). I never tried to use the bundle + oauth + FOSUserBundle.

**Comment by blump** [comment]
sql error is not the problem, the PUT request does not work on its own user object because ObjectEvent returned null. I have not had time , but I'll find a fix. I'll explain in French next week easier for me . Have a nice week end

**Comment by theofidry** [comment]
@blump explain in French if it's too difficult in English, some of us speak French so it's fine.

As for me I'm using the FOSUserBundle fine although with a little error in my logs but with nothing noticeable besides that:

```
Catchable Fatal Error: Argument 1 passed to Dunglas\\ApiBundle\\FosUser\\EventSubscriber::__construct() must implement interface Symfony\\Component\\EventDispatcher\\EventDispatcherInterface, none given, called in \/path\/to\/app\/cache\/dev\/appDevDebugProjectContainer.php on line 463 and defined
```

And I've just checked to update an existing user and the user I'm logged with without any URL parameters and it works fine. So it either comes from a conflict of some kind with Oauth or a problem of configuration.

**Comment by blump** [comment]
Ok the next issue, i speak French :p . After a composer to update now, the subject of his own user id is always null but the PUT is spent properly and not replaced by a POST because the user object is null. I look at it tomorrow, if I can find out why
![capture d ecran 2015-05-10 a 22 35 28](https://cloud.githubusercontent.com/assets/10714122/7556222/5fe4ce60-f768-11e4-992a-ec68acfafcab.png)

**Comment by theofidry** [comment]
@blump any update regarding your issue?

**Comment by marcin-piela** [comment]
I have the same problem.

I installed FosOAuthServerBundle and made FosUser integration with ApiBundle, and now I have that situation:
- Make request for OAuth token with grant_type password (admin user)
- Make Put request for Users/1 (Admin) with Authorization Token (I’m logged as Admin user with this token)
- Response is like the User Entity is empty so there are a validation errors like empty email and username.

I Found that the Class of User Entity from „findOrThrowNotFound” method is:
"Proxies\__CG__\AppBundle\Entity\Profile\User"

But in „deserialize” method in PutAction we send class parameter:
„AppBundle\Entity\Profile\User” - so in ItemNormalizer class we have variable „overrideClass” with false and object cannot be initialize cause it expecting class „AppBundle\Entity\Profile\User” not proxy class.

If I make request for another User (not logged) or when I’m using token with grant_type client_credentials everything is ok. Is it my bad or there is a bug? How fix that?

Thanks
