### ISSUE TITLE
FindOne endpoint

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#72]
The current filters on collections allow to search for entities matching a given criteria. But sometimes we don't want to find *entities*, but *the first entity* matching a criteria. The easiest way to achieve that would be to add an endpoint `/offers/findOne?criteria`. So basically an endpoint on which the filters enabled for the collection are enabled too, but which returns the first entity found, pretty much like we did `/offers?criteria` and then retrieved `hydra:member[0]`.

Do you think this could be added or do you deem it too specific?

**Comment by dunglas** [comment]
What about a search with items by pages set to one? Supporting something like a findOne entry point looks over complicated and is against REST principles.

**Comment by theofidry** [comment]
Yeah but the items by page may be disabled right? Or we can consider that for this case the developer must enabled custom pagination and specify the value but it does not feel right. Since there is no doc for the custom pagination right now I can't check right away.

> Supporting something like a findOne entry point looks over complicated and is against REST principles.

For that point you know a deal more than me^^ Whatever the solution should be it would be great to have it in the doc too.

**Comment by dunglas** [comment]
In REST, there is only resources and collection of resources (lists). It doesn't hurt me if a collection contain only one element.

**Comment by theofidry** [comment]
No I didn't mean the structure of the response, a collection with one item is perfectly fine by me. But the configuration seems a bit more annoying.

**Comment by theofidry** [comment]
I close it for the moment I'll repopen it depending of the configuration required if it's really too much for such simple use case.
