### ISSUE TITLE
Fix filters descriptions

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#74]
At the moment only the filter description (`hydra:search`) of the search filter is well implemented. For the order filter and date filter the description is lacking or invalid.

**Comment by dunglas** [comment]
They look ok to me. What's the issue exactly?

**Comment by theofidry** [comment]
The following IriTemplate seems weird for `string`:
```
"hydra:template": "\/dummies{?id,name,relatedDummy,relatedDummies,order[id],order[name],string}",
...
"hydra:mapping": [
    {
        "@type": "IriTemplateMapping",
        "variable": "string",
        "property": "dummyDate",
        "required": false    
    }
]
```

But it was already here before the merge so maybe it's the expected behaviour. It just seems strange to have `string` here instead of `dummyDate` like the others.

The other issue is for `DateFilter` the description has not been done yet and I'm not sure of the syntax: `dummyDate[<after|before>]`? `dummyDate[after], dummyDate[before]`? what about the case sensitiveness?
