### ISSUE TITLE
Cannot use entity with custom identifier ( != 'id' )

### ISSUE THREAD

**Issue by MLKiiwy** [dunglas/DunglasApiBundle#79]
Actually IriConverter use only a field name 'id' for entity identifier. 

It's an issue, the good solution is to read class metadata from doctrine and use the field maked with @ORM\Id annotation

**Comment by dunglas** [comment]
`id` is hardcoded in some part of the bundle. As a property called `@id` is required by JSON-LD, I can sleep sleep with the requirement of having `$id` property or a `getId()` method.

There is nothing preventing to create `getId()` method even if it's not the property name used by Doctrine. And some edge cases such as composed primary keys are not compatible with JSON-LD anyway.

I don't want to create a hard dependency against Doctrine (we currently use the bundle with other data providers such as Elastic Search, web services...). If you want to make the method used configurable, an entry in https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/ClassMetadata.php looks better to me.

**Comment by MLKiiwy** [comment]
Yes, my PR introduce an hard dependancy with doctrine. I'm looking for a better solution to remove that

**Comment by dunglas** [comment]
A solution:
1. create a `$identifier` property in https://github.com/dunglas/DunglasApiBundle/blob/master/Mapping/ClassMetadata.php and in the relative interface with a default value being `id`
2. create a `DoctrineIdentifierLoader` in https://github.com/dunglas/DunglasApiBundle/tree/master/Mapping/Loader populating that property using your code
3. in IriConverter (and probably in other part of the bundle), use that metadata

What do you think?

**Comment by MLKiiwy** [comment]
I think your solution is better and remove the dependancy with doctrine. 
I write the code and do a PR this afternoon if it's ok ;)

**Comment by dunglas** [comment]
Perfect :)
