### ISSUE TITLE
Cannot register custom resource class

### ISSUE THREAD

**Issue by MLKiiwy** [dunglas/DunglasApiBundle#82]
The sample doesn't work.

In ResourcePass.php => all tagged element with "api.resource" are added to resource_collection (OK :) )
But method call "addItemOperation" and "addCollectionOperation" are added on custom resource wich not implements these method (ResourceInterface not required them)

So, maybe add a check that the new resource implements default resource ? 
Or maybe add options to yml to filter default operation (for having a more simple definition) like : 

    resource.locale:
        class:     "MyBundle\MyCustomResource"
        buildItemOperations: ["GET"]
        buildItemCollectionOperations : ["GET", "POST"] 
        tags:      [ { name: "api.resource" } ]

what do you think ?

**Comment by dunglas** [comment]
Related to #63. I'm working right now for a fix about that.
