### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by soyuka** [dunglas/DunglasApiBundle#87]
I know this is in a heavy development state but I'd be nice to have a changelog instead of reading the commits :).

**Comment by dunglas** [comment]
We will have one one 1.0 beta will be released. And it will happen quickly.

**Comment by soyuka** [comment]
I understand, hope it'll go to beta soon! This bundle is too good for me not to use it -_-.

Close if you wish ;).

**Comment by dunglas** [comment]
Now that Symfony 2.7 has been released, it's a matter of days.

**Comment by soyuka** [comment]
That's nice <3
Le lun. 1 juin 2015 à 17:04, Kévin Dunglas <notifications@github.com> a
écrit :

**Comment by dunglas** [comment]
Changelog introduced in 99e181d1387a9d7f5c995a23c2e38e08dc3c01ce
