### ISSUE TITLE
Handling circular references with a custom normalizer

### ISSUE THREAD

**Issue by theofidry** [dunglas/DunglasApiBundle#93]
Given an entity with has a relation with itself, for instance via the attributes `parent` and `children`, the circular reference is not handled.

I'm not sure if it should be handled natively or not, but if not then I guess we should use a custom normalizer to handle it. In this case there is three problems:
* first, the declaration is quite heavy: since the `@api.json_ld.normalizer.item` requires lots of arguments. While I'm not really against it, since if we require multiple normalizer for such use case, we can declare an abstract one to lighten the declaration. If you prefer that rather than declaring the abstract normalizer in your bundle, I believe this could be added in the doc.
* second: while declaring our own normalizer, we have no choice but to copy/paste the whole normalizer and add our conditional statements to handle the special attributes. It's kind of a pain and I wanted to know if you have any recommendation regarding that.
* third: it is currently not possible to use a custom normalizer since some services are lazy loaded and an error is returned because the class of the proxy object does not match the expected class

In both cases it may be a use case frequent enough to deserve a chapter in the doc. What do you think?

cc/ @Pyrex-FWI

**Comment by dunglas** [comment]
When you said not handler, you mean you get a circular reference from the Symfony Serializer or XDebug recursion limit error? In the first case, it's intended and the circular reference handler provided by Symfony can be used. In the second, it's a bug (1876c6fbb17f9183f3ae934c9b1c156a4b63daf2).

1. I'll take a look
2. There is extensions points provided by the Symfony serializer that should provide enough possibility, including the circular reference handle and custom normalizers. You normally don't have any code to share with the standard normalizer. Do you have a concrete exemple of what you're trying to do?

**Comment by theofidry** [comment]
We reach the recursion limit error (which is for us at 1000). I'll give you an example shortly.

**Comment by theofidry** [comment]
Here's an example:

The entity:

```php
<?php

namespace AppBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @Gedmo\Tree(type="nested")
 * @ORM\Entity(repositoryClass="Gedmo\Tree\Entity\Repository\NestedTreeRepository")
 */
class Dummy
{
    /**
     * @var Dummy The parent.
     * @Gedmo\TreeParent
     * @ORM\ManyToOne(targetEntity="Dummy", inversedBy="children")
     * @ORM\JoinColumn()
     */
    private $parent;

    /**
     * @var Dummy[]
     *
     * @ORM\OneToMany(targetEntity = "Dummy", mappedBy = "parent")
     */
    private $children;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    // other methods
}
```

The normalizer declaration:

```yaml
normalizer.menu:
    class: AppBundle\Serializer\DummyNormalizer
    arguments:
        -  @api.resource_collection
        -  @api.iri_converter
        -  @api.mapping.class_metadata_factory
        -  @api.json_ld.context_builder
        -  @property_accessor
        -  @?api.name_converter
    tags: [ { name: serializer.normalizer, priority: 128 } ]
```

And then in the `DummyNormalizer` we add our if statment to handle specific properties.

**Comment by dunglas** [comment]
But does DummyNormalizer supports circular reference handling?

**Comment by theofidry** [comment]
I'm not sure to understand your question. If the bundle is supposed to handle this kind of circular reference natively then this case just rises a bug. Otherwise we are implementing `DummyNormalizer` to support circular reference handling. But in this case, it raises the 3 points mentioned.

**Comment by dunglas** [comment]
Normalizers built in the bundle should supports it:
https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/ItemNormalizer.php#L103-L105
https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/ItemNormalizer.php#L161

If you don't have similar lines in your custom normalizer, it can't works. It's how the Symfony serializer works.

**Comment by theofidry** [comment]
Ok then we *do* to declare or own normalizer to handle the circular reference?

**Comment by theofidry** [comment]
Fixed via 5f161a2

**Comment by TimothyDalbey** [comment]
I've been trying to follow this example.  Having difficulty.  Here's where I'm at:

`zaius.customNormalizer:
        class: MHE\zaiusBundle\Service\CustomNormalizer
        tags: [ { name: serializer.normalizer, priority: 128 } ]`

and accordingly

`class CustomNormalizer extends AbstractNormalizer
{

    public function __construct(){

        parent::__construct();

        $this -> setCircularReferenceHandler(function ($object) {

            return json_encode(array('id' => $object -> getId()));

        });

    }
`

However, while other elements of my custom normalizer execute as expected, I can't quite get the circular reference handler operating.  Any suggestions?

**Comment by theofidry** [comment]
Hi @TimothyDalbey,

It's unclear what your problem is: are you having a circular reference and you need to handle it or you want to prevent it?

Quite a few things changed this ticket, so if you are having trouble because you have a circular reference, we will need you to provide us more information:

- which version you are using (bundle + Sf + serializer), ideally the list of your installed packages
- your entities service definitions
- the relationships between your entities: where the circular reference occur
- what serializer are you using (if custom what they do)

I'm sorry if it sounds overwhelming but it's a complex problem and there is a lot of factors to consider

**Comment by TimothyDalbey** [comment]
Thank you very much for the quick response.  Very appreciated.  Here we go:

Version:
```
root@c2d938a0b9d8:/tengu/Symfony# app/console --version
Symfony version 2.7.10 - app/dev/debug
```

Packages:
```
  "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "hwi/oauth-bundle": "0.4.*@dev",
        "twitter/bootstrap": "3.*",
        "components/jquery": "1.11.3",
        "bmatzner/fontawesome-bundle": "~4.4",
        "twitter/typeahead.js": "^0.11.1",
        "components/handlebars.js": "^4.0",
        "firebase/php-jwt": "^3.0",
        "knplabs/knp-markdown-bundle": "~1.3",
        "doctrine/doctrine-fixtures-bundle": "dev-master",
        "jms/security-extra-bundle": "dev-master",
        "hirevoice/neo4jphp-ogm": "dev-master",
        "klaussilveira/neo4j-ogm-bundle": "dev-master",
        "everyman/neo4jphp": "dev-master",
        "seferov/aws-bundle": "~1.1",
        "blueimp/jquery-file-upload": "^9.11",
        "oneup/uploader-bundle": "dev-master",
        "friendsofsymfony/rest-bundle": "^1.7",
        "snc/redis-bundle": "2.x-dev",
        "predis/predis": "^1.0",
        "nelmio/cors-bundle": "^1.4"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "phpunit/phpunit": "4.7.*"
    },
```

Pertinent service definitions:
```
framework:
    serializer:
        enabled: true
        enable_annotations: true
```
```
    zaius.customNormalizer:
        class: MHE\zaiusBundle\Service\CustomNormalizer
        tags: [ { name: serializer.normalizer, priority: 128 } ]
```
Entity (parent is what is causing the issue):

```
namespace MHE\zaiusBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="projectgroup",
 *      indexes={
 *      }
 * )
 */
class Projectgroup{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"object_view","group_index","group_view", "organization_view"})
     */
    protected $id;

    //-------------------------------------------------------------------------------

    /**
     * @ORM\OneToMany(targetEntity="Projectgroup", mappedBy="parent")
     * @Groups({"group_view"})
     **/
    private $children;

    /**
     * @ORM\ManyToOne(targetEntity="Projectgroup", inversedBy="children", cascade={"merge", "persist"})
     * @ORM\JoinColumn(name="parent_projectgroup_id", referencedColumnName="id")
     * @Groups({"object_view","group_index","group_view", "organization_view"})
     **/
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity="ProjectgroupUser", mappedBy="projectgroup")
     * @Groups({"group_view"})
     */
...
```

**Comment by TimothyDalbey** [comment]
Oh shoot -  I didn't read very well.  OK -  new ticket it is.

**Comment by jazzzzy** [comment]
@TimothyDalbey I know it's been a while but could you please link the new ticket? I have a similar issue to yours. Thanks

**Comment by meyerbaptiste** [comment]
@jazzzzy: https://github.com/api-platform/core/issues/481
